#!/usr/bin/env bash
set -euo pipefail

prompt() {
  local var_name="$1"
  local label="$2"
  local default_value="${3:-}"
  local input

  if [[ -n "$default_value" ]]; then
    read -r -p "${label} [${default_value}]: " input
    input="${input:-$default_value}"
  else
    read -r -p "${label}: " input
  fi

  export "$var_name=$input"
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

command -v az >/dev/null 2>&1 || die "Azure CLI (az) not found. Install it and retry."
az account show >/dev/null 2>&1 || die "Not logged in. Run: az login"

echo "== Azure Event Hubs setup =="

prompt AZ_REGION "Preferred Azure region (e.g., southcentralus)" "southcentralus"
prompt RG_NAME   "Resource group name" "rg-eventhub-demo"
prompt EH_NAME   "Event Hub name" "eh-ingestion"

BASE_NS="$(echo "ehns-${RG_NAME}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')"
BASE_NS="${BASE_NS:0:30}"
RAND_SUFFIX="$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 6 || true)"
NS_NAME="${BASE_NS}-${RAND_SUFFIX}"

SP_NAME="sp-forzadataout-${RAND_SUFFIX}"

echo
echo "Region:            ${AZ_REGION}"
echo "ResourceGroup:     ${RG_NAME}"
echo "Namespace:         ${NS_NAME}"
echo "EventHub:          ${EH_NAME}"
echo "Service Principal: ${SP_NAME}"
echo

echo "1) Creating resource group..."
az group create \
  --name "${RG_NAME}" \
  --location "${AZ_REGION}" \
  --only-show-errors -o none

echo "2) Creating Event Hubs namespace..."
az eventhubs namespace create \
  --name "${NS_NAME}" \
  --resource-group "${RG_NAME}" \
  --location "${AZ_REGION}" \
  --sku Standard \
  --only-show-errors -o none

echo "3) Creating Event Hub..."
az eventhubs eventhub create \
  --name "${EH_NAME}" \
  --namespace-name "${NS_NAME}" \
  --resource-group "${RG_NAME}" \
  --partition-count 2 \
  --only-show-errors -o none

echo "4) Creating Azure AD App Registration..."
APP_ID="$(az ad app create \
  --display-name "${SP_NAME}" \
  --only-show-errors \
  --query appId -o tsv)"

[[ -n "${APP_ID}" && "${APP_ID}" != "null" ]] || die "Failed to create app registration"

echo "5) Creating Service Principal for the app..."
az ad sp create \
  --id "${APP_ID}" \
  --only-show-errors -o none

echo "6) Adding credential (expires in 28 days to comply with policy)..."
# Policy requires expiry by April 17, 2026 - use 28 days to be safe
if [[ "$(uname)" == "Darwin" ]]; then
  # macOS date command
  START_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  END_DATE="$(date -u -v+28d '+%Y-%m-%dT%H:%M:%SZ')"
else
  # Linux date command
  START_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  END_DATE="$(date -u -d '+28 days' '+%Y-%m-%dT%H:%M:%SZ')"
fi

# Add credential using Microsoft Graph API format
CRED_RESULT="$(az rest \
  --method POST \
  --uri "https://graph.microsoft.com/v1.0/applications(appId='${APP_ID}')/addPassword" \
  --headers "Content-Type=application/json" \
  --body "{\"passwordCredential\": {\"displayName\": \"Generated by setup script\", \"startDateTime\": \"${START_DATE}\", \"endDateTime\": \"${END_DATE}\"}}" \
  --query '{password: secretText}' -o json)"

CLIENT_ID="${APP_ID}"
CLIENT_SECRET="$(echo "${CRED_RESULT}" | grep -oP '"password":\s*"\K[^"]+')"
TENANT_ID="$(az account show --query tenantId -o tsv)"

[[ -n "${CLIENT_SECRET}" && "${CLIENT_SECRET}" != "null" ]] || die "Failed to create credential"

echo "Credential will expire on: ${END_DATE}"

echo "7) Getting Event Hub namespace resource ID..."
NS_RESOURCE_ID="$(az eventhubs namespace show \
  --name "${NS_NAME}" \
  --resource-group "${RG_NAME}" \
  --query id -o tsv)"

echo "8) Assigning 'Azure Event Hubs Data Sender' role to Service Principal..."
az role assignment create \
  --assignee "${CLIENT_ID}" \
  --role "Azure Event Hubs Data Sender" \
  --scope "${NS_RESOURCE_ID}" \
  --only-show-errors -o none

echo "Waiting for role assignment to propagate..."
sleep 10

echo
echo "== Done =="
echo "Event Hubs Namespace:  ${NS_NAME}.servicebus.windows.net"
echo "Event Hub Name:        ${EH_NAME}"
echo "Service Principal:     ${SP_NAME}"
echo
echo "=== Service Principal Credentials (save these securely) ==="
echo "Tenant ID:     ${TENANT_ID}"
echo "Client ID:     ${CLIENT_ID}"
echo "Client Secret: ${CLIENT_SECRET}"
echo
echo "Update your appsettings.json with:"
echo "{"
echo "  \"EventHub\": {"
echo "    \"Enabled\": true,"
echo "    \"Namespace\": \"${NS_NAME}.servicebus.windows.net\","
echo "    \"EventHubName\": \"${EH_NAME}\","
echo "    \"TenantId\": \"${TENANT_ID}\","
echo "    \"ClientId\": \"${CLIENT_ID}\","
echo "    \"ClientSecret\": \"${CLIENT_SECRET}\""
echo "  }"
echo "}"
echo
echo "IMPORTANT: Store the Client Secret securely. You cannot retrieve it again!"
